### ISSUE TITLE
not working with Cisco 3850

### ISSUE THREAD

**Issue by mikesamo** [DE-IBH/cmk_cisco-dom#3]
Hello,

the check dont seem to detect DOM on a Cisco 3850 

Thanks,

**Comment by liske** [comment]
Hi,

I'm able to reproduce your problem (running IOS 03.07.x), but it needs some more debugging to find the root cause.

**Comment by mikesamo** [comment]
Hello,

ok what do you need?

**Comment by mikesamo** [comment]
hey thomas

any update on this ?

thanks

**Comment by liske** [comment]
Hi,

it seems to be an firmware issue - on switches running a recent Denali release it seems to work.
